// packages/svelte/src/stage.svelte
<script lang="ts">
  import { renderModeFor, inertForLayer } from '@gwn-sheet-stack/core';
  import { getStack } from './lib/get-stack';
  import { portal } from './lib/portal';
  import LayerHost from './layer-host.svelte';

  interface Props {
    registry: Record<string, import('svelte').Component<any>>;
    mountWindow?: number;
  }

  const { registry, mountWindow = 3 }: Props = $props();

  const store = getStack();

  // Reactive state via store subscription
  let state = $state(store.getState());
  $effect(() => {
    const unsub = store.subscribe(() => { state = store.getState(); });
    return unsub;
  });

  const topLayer = $derived(state.stack[state.stack.length - 1]);
  const topPresentation = $derived(topLayer?.presentation ?? 'sheet');
  const topDetentId = $derived(topLayer?.detentId);
  const topLayerRef = $derived(
    topLayer
      ? {
          presentation:
            topLayer.presentation === 'sheet'
              ? { kind: 'sheet' as const, largestUndimmedDetentId: undefined, detents: [] }
              : { kind: (topLayer.presentation ?? 'sheet') as 'modal' | 'panel' | 'push' },
        }
      : null,
  );
</script>

{#if typeof document !== 'undefined'}
  <div
    use:portal
    data-sheetstack-host
    style:--ss-stack-depth={state.stack.length - 1}
  >
    {#each state.stack as layer, i (layer.id)}
      {@const indexFromTop = state.stack.length - 1 - i}
      {@const mode = renderModeFor(indexFromTop, topPresentation as any, mountWindow)}
      {@const C = registry[layer.kind]}
      {#if mode !== 'unmount' && C}
        {@const isInert = topLayerRef ? inertForLayer(indexFromTop, topLayerRef, topDetentId) : false}
        <LayerHost layerId={layer.id} hidden={mode === 'hidden'} inert={isInert}>
          <C {...(layer.props as Record<string, unknown> ?? {})} />
        </LayerHost>
      {/if}
    {/each}
  </div>
{/if}

// packages/react/src/stage/Stage.tsx
import React from 'react';
import { createPortal } from 'react-dom';

import { type PresentationKind, inertForLayer, renderModeFor } from '@gwn-sheet-stack/core';

import { LayerContext } from '../layer/LayerContext';
import { LayerHost } from '../layer/LayerHost.tsx';
import { useStackState } from '../stack/context';
import { HiddenPolyfill } from './HiddenPolyfill.tsx';

interface StageProps {
  registry: Record<string, React.ComponentType<Record<string, unknown>>>;
  mountWindow?: number;
  container?: HTMLElement | null;
}

export function Stage({ registry, mountWindow = 3, container }: StageProps) {
  const state = useStackState();
  const topLayer = state.stack[state.stack.length - 1];
  const topPresentation: PresentationKind = topLayer?.presentation ?? 'sheet';
  const topDetentId = topLayer?.detentId;

  const topLayerRef = topLayer
    ? {
        presentation:
          topLayer.presentation === 'sheet'
            ? { kind: 'sheet' as const, detents: [] }
            : { kind: (topLayer.presentation ?? 'sheet') as 'modal' | 'panel' | 'push' },
      }
    : null;

  return createPortal(
    <div data-sheetstack-host data-sheetstack-top-presentation={topPresentation}>
      {state.stack.map((layer, i) => {
        const indexFromTop = state.stack.length - 1 - i;
        const mode = renderModeFor(indexFromTop, topPresentation, mountWindow);

        if (mode === 'unmount') return null;

        const Component = registry[layer.kind];
        if (!Component) return null;

        const isInert = topLayerRef ? inertForLayer(indexFromTop, topLayerRef, topDetentId) : false;

        return (
          <LayerContext.Provider key={layer.id} value={layer.id}>
            <HiddenPolyfill mode={mode}>
              <LayerHost layerId={layer.id} inert={isInert}>
                <Component {...(layer.props as Record<string, unknown>)} />
              </LayerHost>
            </HiddenPolyfill>
          </LayerContext.Provider>
        );
      })}
    </div>,
    container ?? document.body,
  );
}
